version: '3.3'
services:
  api:
    container_name: 'api'
    build: './api'
    ports:
      - '8080:8080'
    volumes:
      - './vendor:/go/src/'
      - './api:/go/src/app'
    depends_on:
      - 'mongo'
    environment:
      - 'MONGO_HOST=mongo:27017'
      - 'MONGO_DB=wisard'
      - 'MONGO_USER=mongoU'
      - 'MONGO_PASSWORD=password'
  web:
    container_name: 'web'
    image: 'nginx:latest'
    ports:
      - '8081:80'
    volumes:
      - '.web:/usr/share/ngin/html'
    depends_on:
      - 'api'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - 27100:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoU
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
